Support infinitely expire value
cayasso/cacheman-memory pull request #5
Opened 2018-04-05 20:19 UTC by tenorok

It seems like support of `-1` for ttl was lost.
Lets restore justice!

2018-04-12 07:48 UTC, tenorok commented
@cayasso what do you think?

2018-04-15 00:34 UTC, cayasso requested changes

2018-04-15 00:34 UTC, cayasso commented on lib/index.js
> +    var expire = -1 === ttl
Can we use `const` instead of `var` here?

2018-04-15 00:34 UTC, cayasso commented on test/index.js
> +  it('should not expire key', function (done) {
Nice!!!

2018-04-15 10:41 UTC, tenorok commented
Thank you for review! I fixed it.

It seems that for Travis we need only Nodejs of version 4, because for older versions it throws error:
```
$ npm install 
ERROR: npm is known not to run on Node.js v3.3.1
You'll need to upgrade to a newer version in order to use this
version of npm. Supported versions are 4, 6, 7, 8, 9. You can find the
latest version at https://nodejs.org/
The command "eval npm install  " failed. Retrying, 2 of 3.
```

2018-04-29 18:06 UTC, tenorok commented
@cayasso how are you?

2018-05-02 20:01 UTC, merged

2018-05-02 20:28 UTC, cayasso commented
1.1.0 is out, thanks for contributing!